owner: kijimaD
repo: upptime

sites:
  - name: roam production -- GitHub Pages
    url: https://kijimad.github.io/roam/
  - name: PDF Viewer -- Private only
    url: https://mypdfs.a9ne.com/
  - name: Dashboard -- Private only
    url: https://kubernetes-dashboard.a9ne.com/
  - name: Wiki -- for family member
    url: https://fin.a9ne.com/

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * 0"
  responseTime: "0 23 * * 0"
  staticSite: "0 1 * * 0"
  summary: "0 0 * * 0"
  updateTemplate: "0 0 * * 0"
  updates: "0 3 * * 0"
  uptime: "0 1 * * *"
